# Generated by Django 2.1 on 2018-08-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180828_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Veiculo'),
        ),
        migrations.AlterField(
            model_name='movimentomensalista',
            name='mensalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Mensalista'),
        ),
        migrations.AlterField(
            model_name='movimentorotativo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pessoa'),
        ),
    ]
